using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace Generators;

[Generator]
public class AutoNotifyGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all fields with [AutoNotify] attribute
        var fieldsWithAttribute = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is FieldDeclarationSyntax,
                transform: static (ctx, _) => GetFieldInfo(ctx))
            .Where(field => field is not null)
            .Collect();

        context.RegisterSourceOutput(fieldsWithAttribute, GenerateProperties);
    }

    private static FieldInfo? GetFieldInfo(GeneratorSyntaxContext context)
    {
        var fieldDecl = (FieldDeclarationSyntax)context.Node;

        foreach (var variable in fieldDecl.Declaration.Variables)
        {
            var fieldSymbol = context.SemanticModel.GetDeclaredSymbol(variable) as IFieldSymbol;
            if (fieldSymbol != null)
            {
                foreach (var attribute in fieldSymbol.GetAttributes())
                {
                    var attrClass = attribute.AttributeClass;
                    if (attrClass?.Name == "AutoNotifyAttribute" ||
                        attrClass?.ToDisplayString() == "WebApi.Attributes.AutoNotifyAttribute")
                    {
                        var classSymbol = fieldSymbol.ContainingType;
                        return new FieldInfo(
                            ClassName: classSymbol.Name,
                            NamespaceName: classSymbol.ContainingNamespace.ToDisplayString(),
                            FieldName: fieldSymbol.Name,
                            FieldType: fieldSymbol.Type.ToDisplayString()
                        );
                    }
                }
            }
        }
        return null;
    }

    private static void GenerateProperties(SourceProductionContext context, ImmutableArray<FieldInfo?> fields)
    {
        var groupedFields = fields
            .Where(f => f != null)
            .GroupBy(f => (f!.Value.ClassName, f!.Value.NamespaceName));

        foreach (var group in groupedFields)
        {
            var (className, namespaceName) = group.Key;
            var properties = new StringBuilder();

            foreach (var fieldInfo in group)
            {
                var fi = fieldInfo!.Value;
                string propertyName = ToPascalCase(fi.FieldName.TrimStart('_'));

                // Generate ONLY the property, NOT the field
                properties.AppendLine($@"
        public {fi.FieldType} {propertyName}
        {{
            get => {fi.FieldName};
            set
            {{
                if (!System.Collections.Generic.EqualityComparer<{fi.FieldType}>.Default.Equals({fi.FieldName}, value))
                {{
                    {fi.FieldName} = value;
                    OnPropertyChanged(nameof({propertyName}));
                }}
            }}
        }}
");
            }

            string source = $@"// <auto-generated/>
using System.ComponentModel;

namespace {namespaceName}
{{
    public partial class {className} : INotifyPropertyChanged
    {{
        public event PropertyChangedEventHandler? PropertyChanged;

        protected virtual void OnPropertyChanged(string propertyName)
            => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
{properties}
    }}
}}";

            context.AddSource($"{className}_AutoNotify.g.cs", SourceText.From(source, Encoding.UTF8));
        }
    }

    private static string ToPascalCase(string input)
    {
        if (string.IsNullOrEmpty(input)) return input;
        return char.ToUpper(input[0]) + input.Substring(1);
    }

    private readonly struct FieldInfo
    {
        public string ClassName { get; }
        public string NamespaceName { get; }
        public string FieldName { get; }
        public string FieldType { get; }

        public FieldInfo(string ClassName, string NamespaceName, string FieldName, string FieldType)
        {
            this.ClassName = ClassName;
            this.NamespaceName = NamespaceName;
            this.FieldName = FieldName;
            this.FieldType = FieldType;
        }
    }
}